[theme]
background = "#191414"
primary = "#989898"
secondary = "#15DCFF"
title = "#FFFFFF"
playing = "#1DB954"
playing_selected = "#191414"
playing_bg = "#000000"
highlight = "#191414"
highlight_bg = "#1DB954"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#191414"
statusbar_progress = "#1DB954"
statusbar_bg = "#1DB954"
cmdline = "#CBFFDE"
cmdline_bg = "#606060"
